name: Scheduled Build

on:
  schedule:
    # Runs at 3 AM UTC every day
    - cron: '0 3 * * *'
  # Optional: allows you to run it manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run build
        run: |
          echo "Running scheduled build..."
          # Replace this with your actual build command
          npm install
          npm run build

