name: Daily Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "*/5 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: PW_DevOps/sesson_18  # ✅ No ./, no extra PW_DevOps

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Check folder structure
        run: |
          echo "PWD: $(pwd)"
          ls -R

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '20.19.0'

      - name: Clean and Install Dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm install

      - name: Run Tests
        run: npm test

      - name: Build React App
        run: npm run build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: react-build
          path: build
